### ISSUE TITLE
RQ_001 로그인

### ISSUE THREAD

**Issue by Seoulice** [s-choory/OfficeMate_ERP#2]
• 사용자는 ID  와 비밀번호를 입력할 수 있는 로그인 화면이 제공된다.
• SpringSecurity 를 적용하여 인증 과정을 구현한다.
•  입력한 ID  와 비밀번호가 데이터베이스에 등록된 유효한 정보인지 SpringSecurity를 통해 확인한다.
•  유효한 정보일 경우 로그인이 허용되어야 한다.
•  로그인 실패 시 적절한 오류 메시지를 출력한다

![스크린샷 2024-05-16 085645](https://github.com/s-choory/OfficeMate_ERP/assets/108114973/2e3f8c09-1a8a-4730-93e2-b48887a6da1d)

**Comment by pilsungk-oss** [comment]
SRS 요구사항에 포함시킨 그림도 여기 이슈에 포함하기 바랍니다.
